version: '3.4'
x-build: &build
  context: .
  dockerfile: Dockerfile

x-shared: &common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEV_SOURCE=${DEV_SOURCE}
  volumes:
    - .:/src/propose
    - ./notebooks:/notebooks
    - ./tests:/tests
  env_file:
    - .env

services:
  base:
    image: propose
    <<: *common
    volumes:
      - .:/src/propose
      - ./scripts:/scripts
      - ./data:/data

  python:
    &python
    image: propose
    entrypoint: [ "python" ]

  train:
    image: propose
    volumes:
      - .:/src/propose
      - ./scripts:/scripts
      - ./data:/data
      - ./configs:/configs
    env_file:
      - .env
    entrypoint: [ "python", "/scripts/train.py" ]

  eval:
    image: propose
    volumes:
      - .:/src/propose
      - ./scripts:/scripts
      - ./data:/data
      - ./configs:/configs
    env_file:
      - .env
    entrypoint: [ "python", "/scripts/eval.py" ]

  preprocess:
    image: propose
    volumes:
      - .:/src/propose
      - ./scripts:/scripts
      - ./data:/data
    entrypoint: [ "python", "/scripts/preprocess.py" ]

  pytest:
    <<: *common
    volumes:
      - .:/src/propose
      - ./tests:/tests
    entrypoint: [ "pytest" ]

  notebook_server:
    <<: *common
    volumes:
      - .:/src/propose
      - ./notebooks:/notebooks
      - ./data:/data
    ports:
      - "8888:8888"
