from .base import BasePose


class Rat7mPose(BasePose):
    def __init__(self,
                 HeadF,
                 HeadB,
                 HeadL,
                 SpineF,
                 SpineM,
                 SpineL,
                 HipL,
                 KneeL,
                 ShinL,
                 HipR,
                 KneeR,
                 ShinR,
                 ElbowL,
                 ArmL,
                 ShoulderL,
                 ElbowR,
                 ArmR,
                 ShoulderR,
                 Offset1,
                 Offset2,
                 **kwargs
                 ):

        super().__init__(
            HeadF=HeadF,
            HeadB=HeadB,
            HeadL=HeadL,
            SpineF=SpineF,
            SpineM=SpineM,
            SpineL=SpineL,
            HipL=HipL,
            KneeL=KneeL,
            ShinL=ShinL,
            HipR=HipR,
            KneeR=KneeR,
            ShinR=ShinR,
            ElbowL=ElbowL,
            ArmL=ArmL,
            ShoulderL=ShoulderL,
            ElbowR=ElbowR,
            ArmR=ArmR,
            ShoulderR=ShoulderR,
            Offset1=Offset1,
            Offset2=Offset2,
        )